package LogicaNegocio;

public enum Paneles {
    REGISTRAR_ASISTENCIA,
    HISTORIAL_ASISTENCIA,
    PROXIMOS_PAGOS_PROFESOR,
    PROXIMOS_PAGOS_ALUMNO,
    MIS_GRUPOS,
    ALUMNOS_GRUPO_PROFESOR,
    ALUMNOS_GRUPO_DIRECTOR,
    PAGOS_ALUMNO,
    PAGOS_PROFESOR,
    PAGOS_CLIENTE,
    PAGOS_TEMPORALES,
    GRUPOS_Y_RENTAS,
    RENTAS,
    CATALOGO_ALUMNOS,
    CATALOGO_PROFESORES,
    CATALOGO_CLIENTES,
    EGRESOS,
    REPORTE;
}
